"""create users and otp_codes tables

Revision ID: 6af9dee7653d
Revises: 
Create Date: 2026-07-21 11:15:44.020170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af9dee7653d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_user_id'), 'otp_codes', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=6), nullable=False),
    sa.Column('role', sa.Enum('SELLER', 'SUPPLIER', 'AGENT', 'MANAGER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'ACTIVE', 'REJECTED', 'SUSPENDED', 'BANNED', name='account_status'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('cin_number', sa.String(length=64), nullable=True),
    sa.Column('cin_photo_front_url', sa.String(length=512), nullable=True),
    sa.Column('cin_photo_back_url', sa.String(length=512), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('fiscal_number', sa.String(length=64), nullable=True),
    sa.Column('primary_depot_name', sa.String(length=255), nullable=True),
    sa.Column('primary_depot_address', sa.String(length=512), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rejection_reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otp_codes_user_id'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
